"""Add onboarding response and background tables

Revision ID: 002
Revises: 001_initial_authentication_tables
Create Date: 2025-01-08 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Note: onboarding_responses table was already created in migration 0001
    # This migration now only ensures the user_backgrounds table has all required fields

    # Update user_backgrounds table if it doesn't have all required fields
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Check if user_backgrounds table exists first
    if inspector.has_table('user_backgrounds'):
        columns = [col['name'] for col in inspector.get_columns('user_backgrounds')]

        if 'hardware_expertise' not in columns:
            op.add_column('user_backgrounds', sa.Column('hardware_expertise', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: onboarding_responses table is managed by migration 0001
    # Only remove the hardware_expertise column if it was added
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if inspector.has_table('user_backgrounds'):
        columns = [col['name'] for col in inspector.get_columns('user_backgrounds')]
        if 'hardware_expertise' in columns:
            op.drop_column('user_backgrounds', 'hardware_expertise')
    # ### end Alembic commands ###