"""increase_refresh_token_size

Revision ID: 0010
Revises: 0009
Create Date: 2025-12-25 12:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Increase the size of the token column in refresh_tokens table
    op.alter_column('refresh_tokens', 'token',
                    existing_type=sa.String(length=255),
                    type_=sa.String(length=500),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the size of the token column in refresh_tokens table
    op.alter_column('refresh_tokens', 'token',
                    existing_type=sa.String(length=500),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    # ### end Alembic commands ###
