"""add_missing_user_columns

Revision ID: 0008
Revises: 0007
Create Date: 2025-12-24 23:22:09.868607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, rename 'name' column to 'full_name' to match the model
    # For PostgreSQL (Neon), we can use ALTER TABLE directly
    op.execute("ALTER TABLE users RENAME COLUMN name TO full_name")

    # Create enum types (using DO block to check if exists)
    # PostgreSQL requires us to check if type exists first
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE userrole AS ENUM ('user', 'moderator', 'admin', 'super_admin');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE userstatus AS ENUM ('inactive', 'active', 'suspended', 'banned');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE authprovider AS ENUM ('email', 'google', 'github', 'apple', 'microsoft');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Add missing columns
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('user', 'moderator', 'admin', 'super_admin', name='userrole'), nullable=False, server_default='user'))
    op.add_column('users', sa.Column('status', sa.Enum('inactive', 'active', 'suspended', 'banned', name='userstatus'), nullable=False, server_default='inactive'))
    op.add_column('users', sa.Column('auth_provider', sa.Enum('email', 'google', 'github', 'apple', 'microsoft', name='authprovider'), nullable=False, server_default='email'))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))

    # Create indexes for performance
    op.create_index('idx_user_email_status', 'users', ['email', 'status'])
    op.create_index('idx_user_role_status', 'users', ['role', 'status'])
    op.create_index('idx_user_auth_provider', 'users', ['auth_provider'])
    op.create_index('idx_user_username', 'users', ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_auth_provider', table_name='users')
    op.drop_index('idx_user_role_status', table_name='users')
    op.drop_index('idx_user_email_status', table_name='users')

    # Drop columns
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'username')

    # Rename 'full_name' back to 'name'
    op.execute("ALTER TABLE users RENAME COLUMN full_name TO name")

    # Drop enum types (optional, can keep for simplicity)
    # op.execute("DROP TYPE IF EXISTS authprovider")
    # op.execute("DROP TYPE IF EXISTS userstatus")
    # op.execute("DROP TYPE IF EXISTS userrole")

    # ### end Alembic commands ###
